export default { 
    palette_colors: [],
    scene_colors: {},
    layers: [],
    mode: "Sculpt",
    tool: "Pen",
    wireframeMode: "Wireframe selected",
    brushSize: 1,
    background: { r: 0, g: 0, b: 0, a: 1 },
    foreground: { r: 255, g: 255, b: 255, a: 1 },
    mirrorX: false,
    mirrorY: false,
    mirrorZ: false,
    mirror: null,
    colorDisplay: null,
    feather:0,
}